version: '3.7'
services:
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa
    ports:
      - "8080:80"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=dvwa
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: dvwa_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dvwa
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
